### PR TITLE
support RENAME TABLE, DROP TABLE, ALTER TABLE RENAME

### PR DESCRIPTION
**Pull request by jgysland**
Adds support for:
* `RENAME TABLE tbl_name TO new_tbl_name [, tbl_name2 TO new_tbl_name2] ...`
* `ALTER TABLE RENAME {INDEX|KEY} old_index_name TO new_index_name`
* `ALTER TABLE RENAME [TO|AS] new_tbl_name`

I took the liberty of moving `_database_name` from `mysqlparse.grammar.alter_table` to `mysqlparse.grammar.identifier` and renaming it to `database_name_syntax`. I'm open to putting it somewhere else or calling it something else, but it didn't make sense to import a private name from `alter_table.py` into `rename_table.py`. (And in fact, there are places it's not being used where MySQL *does* support having a database name, so it may be good to use it even more places.)

I don't really care about `ALTER TABLE RENAME {INDEX|KEY}`, but not including a way to parse these statements makes pyparsing throw a `ParserException` with a long and incomprehensible message (and a traceback that doesn't anywhere point to a line of code in the `mysqlparse` namespace) when [this precaution](https://github.com/seporaitis/mysqlparse/compare/master...jgysland:support-rename-table?expand=1#diff-4d5493d276fbc1ba528c2a8376444e1cR118) is taken and it attempts to parse `RENAME INDEX` or `RENAME KEY`.

### CODE REVIEW

**Comment by jgysland** [comment]
Added a commit to support `DROP TABLE` as well. I would have made a separate PR but for the `_database_name` -> `database_name_syntax` rename/move.

**Comment by jgysland** [comment]
The CI failure seems to be related to an error in the environment setup. I don't know how to get it to re-run.

**Comment by adamchainz** [comment]
Rerun by rebuilding your commit with `git commit --amend --allow-empty` and then `git push --force`, Travis will see the branch as updated and restart. You're right it's probably a random failure.

**Comment by jgysland** [comment]
Well this is fun. Now we've got a failure (in a different environment) with ... a missing interpreter?
`ERROR:   py33: InterpreterNotFound: python3.3`

**Comment by adamchainz** [comment]
Probably related to https://docs.travis-ci.com/user/precise-to-trusty-migration-guide/ , @seporaitis can you try fixing in another PR? I don't think testing with 3.3 upwards is really necessary, probably safe to just test on 3.6.

**Comment by seporaitis** [comment]
Sorry for being slow on this. I'll have a look at this PR and fixing the issue this week.

**Pull request merged**
